routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('appointments', 'AppointmentsController')->middleware('verified');

resources/views/about.blade.php
<html>
    <head>
        <title>Sobre nosotros</title>
        <link href='//fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 0;
                padding: 0;
                width: 100%;
                height: 100%;
                display: table;
                font-weight: 100;
                font-family: 'Lato';
            }
            .container {
                text-align: center;
                display: table-cell;
                vertical-align: middle;
            }
            .content {
                text-align: center;
                display: inline-block;
            }
            .title {
                font-size: 96px;
                margin-bottom: 40px;
                text-decoration: underline;
            }
            .quote {
                font-size: 24px;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }

        </style>
    </head>
    <body>

<div class="flex-center position-ref full-height">
                <div class="top-right links">
                    <a href="{{ url('/') }}">Volver al inicio</a>
                </div>

            <div class="content">
                <div class="title">Gestión de la pista de padel online</div>
                <div>¡Bienvenidos al gestor de la pista de padel online de nuestra comunidad de montepinar!</div>
				<div>En vista de que solo Fina y Antonio usaban la pista de padel de nuestra comunidad nuestro presidente (Bruno Quiroga) ideó la idea de automatizar la reserva mediante una web online y una app Android las condiciones para la reserva son las siguientes:</div>
				<div>
					<ol>
						<li>Cada vecino podrá realizar una reserva diaria como máximo.</li>
						<li>Cada reserva tendrá una duración máxima de 2 horas.</li>
						<li>Se podrá reservar la pista con 7 días de antelación, como máximo.</li>
						<li>La pista estará disponible diariamente de 9 a 23 horas.</li>
					</ol>
				</div>
				<div>Espero que con esto todos podamos hacer un uso de la pista y que cese el rayamiento de coches en el parking (Sabemos que es usted Fina).</div>
            </div>
        </div>
    </body>
</html>

</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Bienvenido al gestor de reservas <?php echo Auth::user()->name; ?>.</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
<center>
		    <div class="content" style="width: 100%;">
                        <div class="title m-b-md">
                            La que se avecina gestor de reservas ©JDamianCabello  2019-<?php echo date("Y"); ?>
                        </div>

                        <div class="links">
                            <a class="btn btn-success" href="{{ route('appointments.create') }}" style="margin: 10px;"> Crear una nueva reserva</a>
                            <a class="btn btn-success" style="margin: 10px; font-color: white; background: #4fc3f7; border: 1px solid #4fc3f7;" href="{{ route('appointments.index') }}"> Mostrar reservas</a>
                        </div>
                    </div>
</center>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection