routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/about', function () {
    return view('about');
});

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('appointments', 'AppointmentsController')->middleware('verified');

app/Appointment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Appointment extends Model
{
    protected $fillable = ['day', 'timestart', 'timefinish', 'user_id'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/AppointmentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Appointment;
use Exception;
use App\Mail\NewAppointmentEmail;
use Illuminate\Support\Facades\Mail;

class AppointmentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $appointments = Appointment::where('user_id', Auth::user()->id)->get();
        return view('appointments.index', compact('appointments'));
    }
public function invitation() { return view('appointments.invite', compact('appointment'));}
    /**
    * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('appointments.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $request->validate([
        'day'=>'required|date',
        'timestart'=> 'required|integer',
        'timefinish' => 'required|integer'
      ]);

      $appointment = new Appointment([
        'day' => $request->get('day'),
        'timestart'=> $request->get('timestart'),
        'timefinish'=> $request->get('timefinish'),
        'user_id' => Auth::id()
      ]);

      try {
      $appointment->save();
      $status = "success";
      $message = 'Reserva creada.';
      } catch (Exception $e) {
      	$status = "error";
	$str = $e->getMessage(); $from_char = '#'; $to_char = '@';
	$from_pos = strpos( $str, $from_char );
	$blank_space_pos = strpos( $str, ' ',  $from_pos );
	$to_pos = strpos( $str, $to_char, $blank_space_pos );
	$message = substr( $str, $from_pos + 1, $to_pos - $from_pos - 1);
      }

      $to = Auth::user()->email;
      try {
            Mail::to($to)->send(new NewAppointmentEmail($appointment));
            $message = $message . " y se le ha enviado un correo";
      } catch (Exception $exception) {
          $status = "error";
          $message = $message . ', y no se le envió el correo. Error: ' . $exception->getMessage();              
      }

      return redirect('/appointments')->with($status, $message);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $appointment = Appointment::findOrFail($id);

        return view('appointments.edit', compact('appointment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $request->validate([
        'day'=>'required|date',
        'timestart'=> 'required|integer',
        'timefinish' => 'required|integer'
      ]);

      $appo = Appointment::findOrFail($id);
      $appo->day = $request->get('day');
      $appo->timestart = $request->get('timestart');
      $appo->timefinish = $request->get('timefinish');

      try {
      $appo->save();
      $status = "success";
      $message = 'La reserva se editó correctamente.';
      } catch (Exception $e) {
        $status = "error";
        $str = $e->getMessage(); $from_char = '#'; $to_char = '@';
        $from_pos = strpos( $str, $from_char );
        $blank_space_pos = strpos( $str, ' ',  $from_pos );
        $to_pos = strpos( $str, $to_char, $blank_space_pos );
        $message = substr( $str, $from_pos + 1, $to_pos - $from_pos - 1);
      }
      return redirect('/appointments')->with($status, $message);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
     $appo = Appointment::find($id);
     $appo->delete();

     return redirect('/appointments')->with('success', 'La reserva ha sido eliminada.');
    }
}

resources/views/appointments/create.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div id="createappointment" style="width: 100%; padding: 30px;">
<div class="card uper">
  <div class="card-header">
    Crear una reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('appointments.store') }}">
          <div class="form-group">
              @csrf
              <label for="day">Dia</label>
              <input type="date" min="{{date('Y-m-d')}}" required class="form-control" name="day"/>
          </div>
          <div class="form-group">
              <label for="timestart">Hora de inicio</label>
              <input required min="9" max="22" type="number" class="form-control" name="timestart"/>
          </div>
          <div class="form-group">
              <label for="timefinish">Hora de fin (10 equivale a 10:59)</label>
              <input min="10" required max="22" type="number" class="form-control" name="timefinish"/>
          </div>
          <button type="submit" class="btn btn-primary">Crear</button>
          <a class="btn btn-secondary" href="{{ route('appointments.index') }}"> Cancelar</a>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/appointments/edit.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Editar reserva
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('appointments.update', $appointment->id) }}">
        @method('PUT')
        @csrf
        <div class="form-group">
          <label for="day">Dia</label>
          <input type="date" required min="{{date('Y-m-d')}}" class="form-control" name="day" value={{ $appointment->day }} />
        </div>
        <div class="form-group">
          <label for="timefinish">Hora de inicio</label>
	  <input required type="number" min="9" max="22" class="form-control" name="timestart" value={{ $appointment->timestart }} />
        </div>
        <div class="form-group">
	  <label for="timefinish">Hora de fin (10 equivale a 10:59)</label>
          <input required type="number" min="10" max="22" class="form-control" name="timefinish" value={{ $appointment->timefinish }} />
        </div>
        <button type="submit" class="btn btn-primary">Actualizar</button>
        <a class="btn btn-secondary" href="{{ route('appointments.index') }}"> Cancelar</a>
      </form>
  </div>
</div>
@endsection

resources/views/appointments/index.blade.php
@extends('layouts.app')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div id="myappointments" style="width: 100%; padding: 30px;">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Listado reservas</h2>
        </div>
        <div class="pull-right" align="right">
                <a class="btn btn-success mr-4 mb-2" href="{{ route('appointments.create') }}"> Crear nueva reserva</a>
        </div>
    </div>
</div>

<div class="uper">
  @if (session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  @if (session()->get('error'))
    <div class="alert alert-danger">
      {{ session()->get('error') }}  
    </div><br />
  @endif

  <div style="width: 100%; overflow-x: scroll;">
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Numero reserva</td>
          <td>Dia</td>
          <td>Hora inicio</td>
          <td>Hora fin</td>
          <td colspan="2"></td>
        </tr>
    </thead>
    <tbody>
        @foreach($appointments as $appointment)
        <tr>
            <td>{{$appointment->id}}</td>
            <td>{{$appointment->day}}</td>
            <td>{{$appointment->timestart}}:00</td>
            <td>{{$appointment->timefinish}}:59</td>
            <td><a href="{{ route('appointments.edit',$appointment->id)}}" class="btn btn-primary">Editar reserva</a></td>
            <td>
                <form action="{{ route('appointments.destroy', $appointment->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Borrar reserva</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  </div>
<div>
</div>
@endsection